Update Seller Profile
MATTALUI/wdd430-group3 pull request #23
Opened 2024-05-26 01:12 UTC by cou23001

2024-05-29 02:34 UTC, MATTALUI requested changes
Most of my comments are optional, but I can't approve with a chunk of the package-lock missing. That indicates an error somewhere that will cause breakages in the deployment.

2024-05-29 02:34 UTC, MATTALUI commented on package-lock.json
> -  },
This should not change without a package.json change. Please investigate this before merging or it will break the app.

2024-05-29 02:34 UTC, MATTALUI commented on src/app/sellers/[id]/page.tsx
> +          {user.description || "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras maximus metus eu auctor venenatis. Cras ullamcorper lectus sit amet mi maximus, ac lobortis orci feugiat.
The lorem ipsum was just a place holder. If we are storing the data for user profiles now we should remove it.

2024-05-29 02:34 UTC, MATTALUI commented on src/app/sellers/edit/[id]/page.tsx
> +const formDataSchema = z.object({
We should probably call this something more descriptive. Maybe something like `updateProfileSchema`

2024-05-29 02:34 UTC, MATTALUI commented on src/app/sellers/edit/[id]/page.tsx
> +        'use server'
You don't need to use `use server` here if you add this function to the `actions.ts` file.

2024-05-29 02:34 UTC, MATTALUI commented on src/lib/actions.ts
> +export async function updateFormData (id: string, formData: any)  {
Rename this function since you're updating a user profile and not form data.

2024-05-29 02:34 UTC, MATTALUI commented on src/app/sellers/edit/[id]/page.tsx
> +    const errors = searchParams.errors ? JSON.parse(decodeURIComponent(searchParams.errors)) : [];
We should not be adding error messaged to the search params. they should be return values from the action that we can then act on. I believe `useFormState` will do this for us.

2024-05-29 02:34 UTC, MATTALUI commented on src/lib/actions.ts
> +export async function updateFormData (id: string, formData: any)  {
Also, don't use `any`

2024-05-29 02:34 UTC, MATTALUI commented on src/lib/actions.ts
> +export async function updateFormData (id: string, formData: any)  {
Why is the `id` input different than the rest of the data?

2024-05-29 02:34 UTC, MATTALUI commented on src/lib/data.ts
> +    // Filter out undefined values to avoid setting them in the database
Shouldn't zod be doing this for us with the validations?

2024-05-29 02:34 UTC, MATTALUI commented on src/lib/data.ts
> +    return { message: true, updatedUser: result };
These return values will cause issues down the line because the type of `message` is inconsistent. If it's a success it'll be a boolean and if it's a failure it'll be a string. We should make the return type the same regardless of the internal functions.

2024-05-29 21:58 UTC, cou23001 commented on src/app/sellers/edit/[id]/page.tsx
> +const formDataSchema = z.object({
It has been updated

2024-05-29 22:01 UTC, cou23001 commented on src/app/sellers/[id]/page.tsx
> +          {user.description || "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras maximus metus eu auctor venenatis. Cras ullamcorper lectus sit amet mi maximus, ac lobortis orci feugiat.
It was removed

2024-06-03 04:15 UTC, cou23001 commented on src/lib/data.ts
> +    return { message: true, updatedUser: result };
It has been updated

2024-06-03 04:15 UTC, cou23001 commented on src/lib/data.ts
> +    // Filter out undefined values to avoid setting them in the database
It has been updated

2024-06-03 19:49 UTC, cou23001 commented on src/app/sellers/edit/[id]/page.tsx
> +        'use server'
it has been changed. It includes a new component UserProfileClient which does the job

2024-06-03 19:50 UTC, cou23001 commented on src/app/sellers/edit/[id]/page.tsx
> +    const errors = searchParams.errors ? JSON.parse(decodeURIComponent(searchParams.errors)) : [];
it has been changed. It includes a new component UserProfileClient which does the job

2024-06-03 19:50 UTC, cou23001 commented on src/lib/actions.ts
> +export async function updateFormData (id: string, formData: any)  {
It has been done. Any still a pending issue

2024-06-04 01:51 UTC, cou23001 commented on package-lock.json
> -  },
It has been corrected

2024-06-04 01:56 UTC, MATTALUI approved these changes

2024-06-04 02:57 UTC, merged